---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: simple-routing
spec:
  hosts:
  - app.example.com
  gateways:
  - sample-app
  http:
  - route:
    - destination:
        host: sample-app
        port:
          number: 8080
