repositories:
  - name: istio-official
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    chart: istio-official/base
    version: 1.19.0-alpha.1

  # - name: istio-misc
  #   namespace: istio-system
  #   chart: ../charts/istio-misc
  #   disableValidation: true
  #   needs:
  #     - /istio-base

  - name: istiod
    namespace: istio-system
    chart: istio-official/istiod
    version: 1.19.0-alpha.1
    wait: true
    values:
      - ../values/istiod.values.yaml

  - name: istio-ztunnel
    namespace: istio-system
    chart: istio/ztunnel
    version: 1.19.0-alpha.1
    needs:
      - istio-system/istiod
    values:
      - ../values/ztunnel.values.yaml

  - name: istio-cni
    namespace: istio-system
    chart: istio/cni
    version: 1.19.0-alpha.1
    needs:
      - istio-system/istiod
    values:
      - ../values/istio_cni.values.yaml
