repositories:
  - name: istio-official
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    chart: istio-official/base
    version: 1.19.0-alpha.1

- name: istiod
  namespace: istio-system
  chart: istio-official/istiod
  version: 1.19.0-alpha.1
  wait: true
  values:
  - ../values/istiod.values.yaml

  - name: istiod
    namespace: istio-system
    chart: istio-official/istiod
    version: 1.19.0-alpha.1
    wait: true
    values:
      - ../values/istiod.values.yaml

  - name: istio-ztunnel
    namespace: istio-system
    chart: istio-official/ztunnel
    version: 1.19.0-alpha.1
    needs:
      - istio-system/istiod
    values:
      - ../values/ztunnel.values.yaml

  - name: istio-cni
    namespace: istio-system
    chart: istio-official/cni
    version: 1.19.0-alpha.1
    needs:
      - istio-system/istiod
    values:
      - ../values/istio_cni.values.yaml
