# see: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubernetes-without-kube-proxy
kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
# ensure pods roll when configmap updates
rollOutCiliumPods: true
# see: https://docs.cilium.io/en/latest/observability/visibility/#layer-7-protocol-visibility
endpointStatus:
  enabled: true
  status: policy
ingressController:
  enabled: true
  # default is ingress-nginx
  default: false
  enforceHttps: false
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 31080
    secureNodePort: 31443
