---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: curl-deny
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: curl
    version: "1.0.0"
  name: curl-deny
spec:
  serviceAccountName: curl-deny
  terminationGracePeriodSeconds: 0
  containers:
  - name: curl
    image: curlimages/curl
    command:
      - "/bin/sleep"
      - "1h"
    imagePullPolicy: IfNotPresent
    resources: 
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 64Mi
  restartPolicy: Never
