repositories:
- name: kiali
  url: https://kiali.org/helm-charts

releases:
- name: istio-prometheus-monitors
  namespace: prometheus
  chart: ../charts/prometheus-monitor

- name: kiali-server
  namespace: istio-system
  createNamespace: true
  chart: kiali/kiali-server
  version: 1.74.0
  values:
  - ../values/kiali.values.yaml
