repositories:
- name: kiali
  url: https://kiali.org/helm-charts

releases:
- name: kiali-server
  namespace: istio-system
  createNamespace: true
  chart: kiali/kiali-server
  version: 1.74.0
  values:
  - ../values/kiali.values.yaml
