# see: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubernetes-without-kube-proxy
kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
# ensure pods roll when configmap updates
rollOutCiliumPods: true
