---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: color-gw
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw-color
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: color-route-1
spec:
  parentRefs:
  - name: color-gw
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /color
    backendRefs:
    - kind: Service
      name: handson-blue
      port: 8080
      weight: 50
    - kind: Service
      name: handson-yellow
      port: 8080
      weight: 50
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-yellow
  name: handson-yellow
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: handson
    color: yellow

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-blue
  name: handson-blue
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: handson
    color: blue
