name: istio-ingressgateway
imagePullPolicy: IfNotPresent
autoscaling:
  enabled: false
labels:
  app.kubernetes.io/part-of: istio
resources:
  limits:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
