name: istio-ingressgateway
imagePullPolicy: IfNotPresent
autoscaling:
  enabled: false
service:
  type: ClusterIP
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
