name: istio-ingressgateway
imagePullPolicy: IfNotPresent
autoscaling:
  enabled: false
labels:
  app.kubernetes.io/part-of: istio
resources:
  limits:
    cpu: 100m
    memory: 128Mi
service:
  type: NodePort
  ports:
  - port: 15021
    targetPort: 15021
    name: status-port
    protocol: TCP
  - port: 80
    targetPort: 8080
    nodePort: 18080
    name: http2
    protocol: TCP
  - port: 443
    targetPort: 8443
    nodePort: 18443
    name: https
    protocol: TCP
