repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
releases:
  - name: otel-collector
    namespace: opentelemetry
    chart: open-telemetry/opentelemetry-collector
    version: 0.69.2
    values:
      - otel-collector-values.yaml
  - name: otel-collector-cluster
    namespace: opentelemetry
    chart: open-telemetry/opentelemetry-collector
    version: 0.69.2
    values:
      - otel-collector-cluster-values.yaml
