---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-cilium
  name: handson
  namespace: handson-cilium
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: handson-cilium

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-cilium
  name: handson-blue
  namespace: handson-cilium
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: handson-cilium
    color: blue

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: handson-cilium
  name: handson-yellow
  namespace: handson-cilium
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: handson-cilium
    color: yellow
