istiod:
  global:
    imagePullPolicy: IfNotPresent
    logAsJson: true
    defaultPodDisruptionBudget:
      enabled: false
  pilot:
    autoscaleEnabled: false
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    enablePrometheusMerge: true
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    outboundTrafficPolicy:
      mode: ALLOW_ANY
