repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana-tempo
  namespace: monitoring
  createNamespace: true
  chart: grafana/tempo-distributed
  version: 1.9.9
  values:
    - -values.yaml